name: sportshop
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter_swiper_null_safety: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_form_builder: ^9.1.1
  provider: ^6.0.5
  google_maps_flutter: ^2.12.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets\images\82sports.jpg
    - assets\images\ABA.png
    - assets\images\ACLEDA.png
    - assets\images\bakong.jpg
    - assets\images\Binance.png
    - assets\images\PiPay.png
    - assets\images\truemoney.png
    - assets\images\wing.png
    - assets\images\cam.png
    - assets\images\nike.png
    - assets\images\adidas.png
    - assets\images\logo.png
    - assets\images\main_photo.png
    - assets\images\logo82.png
    - assets\images\multisport.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
  
   
